<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.8.5 setup script
 * Date: Tue, 02 Apr 2019 22:35:30 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'Dadam1997Dadam1997';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'f33E]YvXLX#}y`7:LPV$F^7K-xkExhp';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>